### ISSUE TITLE
[Major] You can click next without answering on quiz 

### ISSUE THREAD

**Issue by yiuchungcheung** [info442-sp21/f-team#48]
**Describe the bug**
On the quiz section, users are allowed to click the right arrow without answering questions. 

**To Reproduce**
1. Go to 'quiz' tab
2. Click on 'start'
3. Do not click on any of the answers, keep clicking on right arrow until quiz ends

**Expected behavior**
There should be some sort of validation requiring users to answer the questions and preventing them from moving on to next steps if they haven't answered yet

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser Chrome
 - Version 90.0.4430.212

**Comment by sienasc** [comment]
Fixed

**Comment by cherimarie** [comment]
Since skipping a question doesn't result in not getting suggestions at the end, I think this is a minor issue, not major.

**Comment by ndemmel** [comment]
Commit that solved this issue: https://github.com/info442-sp21/f-team/commit/88b7906e40be20b02ddf51e58d2ba8b427f7f46b
