### ISSUE TITLE
[minor] Searching does not work with 'Enter' button. 

### ISSUE THREAD

**Issue by kristina-te** [info442-sp21/f-team#49]
**Minor Bug**
In the search bar, the enter button does not search for the specific plant.

**To Reproduce**
1. Go to 'Catalogue'.
2. Click on the search bar.
3. Type in 'Peace Lily'.
4. Hit 'Enter' key.

**Expected behavior**
I expected to see the Peace Lily card pop up, but still got all cards in the catalogue instead :( Not sure if it's just my computer or keyboard issue. 

**Desktop (please complete the following information):**
 - OS: macOS Big Sur Version 11.3
 - Browser Chrome Version 90.0.4430.212 (Official Build) (x86_64)

**Comment by ndemmel** [comment]
Duplicates: https://github.com/info442-sp21/f-team/issues/67
https://github.com/info442-sp21/f-team/issues/51

**Comment by sienasc** [comment]
I can't figure this one out. If anyone has any ideas.

**Comment by cherimarie** [comment]
Code suggestion: just make this a normal form, rather than link and input. 
https://github.com/info442-sp21/f-team/blob/main/docs/plantFinder.html#L47

Change to something like:
```
<form onsubmit="displayPlants()">
<div class="searchbutton">
<button type="submit"><img class="searchIcon" id="searchIcon" src="img/noun_Search_3923148.png" alt="Search icon"></a>
</div>
<input type="text" name="searchBar" id="searchBar" placeholder="click icon to search">
</form>
```

**Comment by sienasc** [comment]
Fixed!

**Comment by ndemmel** [comment]
Commit that fixed this issue: https://github.com/info442-sp21/f-team/commit/d34a8aec33f45e5e6afeb2ef5d3358418ea7ca57
