### ISSUE TITLE
[Minor] Website on mobile, picture("7 plants for small living space") is out of screen

### ISSUE THREAD

**Issue by bphan23** [info442-sp21/f-team#50]
* Severity -  Major
* When uploaded the website on mobile device, the picture ("7 plants for small living space") is out of the screen.
* Used - Safari on the iPhone 11 
* CSS styling to make the image readjust on smaller devices.
* Can't see the full picture, half of it is off the screen.
* Expected to be able to see everything I see when opening in on a desktop or laptop.

**Comment by dorilusions** [comment]
Changed to minor because after recreating the bug, the article was still accessible and it just looked visually bad (usability issue).

**Comment by cherimarie** [comment]
Agreed that this is minor if the page content is still usable.

**Comment by dorilusions** [comment]
Fixed!

**Comment by ndemmel** [comment]
Commit that fixed this issue: https://github.com/info442-sp21/f-team/commit/6cb5920aa6271465f4457ae7a7dda991a5eab55e
