### ISSUE TITLE
The search feature does not work

### ISSUE THREAD

**Issue by tichx** [info442-sp21/f-team#51]
**Describe the bug**
On the catalog page, the search feature does not return appropriate responses no matter what the user input is.

**To Reproduce**
1. Go to 'Catalog' page
2. Enter strings on the search bar
3. Nothing goes back

**Expected behavior**
A list of plants have names matched in the search string

**Current behavior**
Nothing happens after the search term is entered

**Screenshots**
<img width="1503" alt="WX20210525-140539@2x" src="https://user-images.githubusercontent.com/12144060/119568421-5a0a4800-bd62-11eb-8afc-449689da5626.png">
<img width="1607" alt="WX20210525-140557@2x" src="https://user-images.githubusercontent.com/12144060/119568446-5bd40b80-bd62-11eb-835b-fb46b5766866.png">

**Desktop (please complete the following information):**
- Device: MacBook Pro (15-inch, 2018)
 - OS: Mac OS Big Sur 11.3.1
 - Browser: Chrome
 - Version: Version 90.0.4430.212 (Official Build) (x86_64)

**Additional context**

**Comment by ndemmel** [comment]
Duplicate. Minor bug- the search function does work, users need to click on the magnifying glass icon instead of pressing 'enter' on their keyboard.
