### ISSUE TITLE
[Minor] Navbar and image header not taking up the full width of page when opening up on a mobile device.

### ISSUE THREAD

**Issue by bphan23** [info442-sp21/f-team#52]
* Severity - Major
* When uploaded the website on a mobile device, the navbar and header image was not taking up the width of the whole page.
* Used - Safari on the iPhone 11
* CSS styling to make the navbar and image readjust on smaller devices.
* Image and navbar only take up 3/4 of the page's width so there's empty whitespace to the right.
* Expected to be able to see everything I see when opening in on a desktop or laptop.

**Comment by dorilusions** [comment]
Changed to minor because navbar and image header are still usable and visible, just (again) look pretty bad on mobile and as such is more of a usability issue.

**Comment by sienasc** [comment]
fixed

**Comment by ndemmel** [comment]
Commit that fixed this issue: https://github.com/info442-sp21/f-team/commit/e0595a973a3954e05550fee8119449499ba4d208
