### ISSUE TITLE
[Minor] Catalogue screen does not scale down on mobile screens

### ISSUE THREAD

**Issue by ashshah1** [info442-sp21/f-team#53]
**Describe the bug**
On inspect, when looking at the catalogue page on mobile, the images do not shrink to fit screen size and the font also remains large.

**To Reproduce**
1. Inspect using developer tools, and toggle down screen size to iPhone X
<img width="348" alt="Screen Shot 2021-05-25 at 2 10 53 PM" src="https://user-images.githubusercontent.com/55997736/119569012-05b39800-bd63-11eb-9d18-398f701b343b.png">

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [mac OS]
 - Browser [Chrome]

**Comment by sienasc** [comment]
fixed

**Comment by ndemmel** [comment]
Commit that fixed this issue: https://github.com/info442-sp21/f-team/commit/e0595a973a3954e05550fee8119449499ba4d208
