### ISSUE TITLE
Can't move to next question in quiz

### ISSUE THREAD

**Issue by juliashull** [info442-sp21/f-team#56]
**Describe the bug**
When I click to the quiz, and try to answer question one - I select my answer but nothing pops up to move to the next question. I can see that my answer was selected because it is green but I don't know how to get to the next question.

**To Reproduce**
1. Go to quiz
2. Click answer for question 1
3. Try to go to next question but 

**Expected behavior**
Expected to be able to move onto next question.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by juliashull** [comment]
Update: I had to zoom out in order to see the next button. 

Additionally, there should be an option to go back to the previous questions to answer.

**Comment by ndemmel** [comment]
Marking as a duplicate, though this issue addresses two things at once. The duplicate issue (implementing a back button on the quiz) was left as a comment on an original issue. The original issue, which is not a duplicate, will be worked on.

**Comment by ndemmel** [comment]
Issue #77  is a duplicate of this issue.
