### ISSUE TITLE
[Minor] Question 5 is labeled with a 4 on the quiz

### ISSUE THREAD

**Issue by juliashull** [info442-sp21/f-team#59]
**Describe the bug**
Question 5 is labeled as Question 4 on the Quiz.

**To Reproduce**
1. Go through the quiz and click to the end

**Expected behavior**
Expect it to say question 5 since it says "5/5" below it

**Screenshots**
![image](https://user-images.githubusercontent.com/46457161/119571284-0568cc00-bd66-11eb-8131-c86451b80992.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by dorilusions** [comment]
Marked as minor as this is an small cosmetic bug.  This is easy enough to fix and will be changed shortly!

**Comment by dorilusions** [comment]
Fixed!

**Comment by ndemmel** [comment]
Commit that fixed this issue: https://github.com/info442-sp21/f-team/commit/549a988e23c983132f7403bace037761befbb299
