### ISSUE TITLE
New feature request: Allow user to see selected filters

### ISSUE THREAD

**Issue by abq14** [info442-sp21/f-team#61]
Right now in the catalogue, users can select multiple filters, but the page doesn't display which filters have been selected. 

It would be nice if you let users select filters using checkboxes to make it easier to keep track of which filters were selected. This would also make it easier to understand which filters can be unselected.

**Comment by ndemmel** [comment]
Duplicate: https://github.com/info442-sp21/f-team/issues/75

**Comment by cherimarie** [comment]
For grading purposes, this is the original report.
