### ISSUE TITLE
Home screen does not scale down on mobile 

### ISSUE THREAD

**Issue by SandyHsiao** [info442-sp21/f-team#62]
Severity: major
Description: By inspecting using a chrome browser and applying iPhone mobile screen size, the page does not scale down and fit the mobile screen.
Reproduce: enter the website, using inspect development tool, select and applied iPhone mobile screen size
Environment: Mac OS Catalina, Chrome browser

**Comment by sienasc** [comment]
Repeat of issue #50 , which we will be doing.
