### ISSUE TITLE
[Minor] Plant 'card' is not clickable

### ISSUE THREAD

**Issue by atnguyenduy** [info442-sp21/f-team#65]
**Describe the bug**
The plant card is not clickable. Only the 'Learn more' is clickable. 

**To Reproduce**
1. Go to 'https://info442-sp21.github.io/f-team/plantFinder.html'
2. Click on any plant card (not on 'Learn more')

**Expected behavior**
Expect plan card to change to a different website when clicked. 

**Screenshots**
![image](https://user-images.githubusercontent.com/41980535/119572194-3c8bad00-bd67-11eb-883d-ca6c91822f74.png)

**Desktop (please complete the following information):**
Device: Lenovo Thinkpad laptop
Windows 10 Enterprise / Version 20H2 / OS build 19042.804
Browser: Edge

**Comment by sienasc** [comment]
We will not be implementing this feature. And it is a duplicate
