### ISSUE TITLE
[Major] Search has no submit button

### ISSUE THREAD

**Issue by jordanjones243** [info442-sp21/f-team#67]
**Describe the bug**
When trying to search a plant in the catalogue, there is no place to submit the search.

**To Reproduce**
1. Go to https://info442-sp21.github.io/f-team/plantFinder.html
2. Click on the search bar
3. Type in a plant to search
4. See that there is no way to submit the search

**Expected behavior**
There should be a button to click on when a person wants to complete a search or an indication that their search is being processed. When doing a search, the page is not responsive at all and there is no way to tell if the search is being processed.

**Desktop (please complete the following information):**
 Google Chrome Version 89.0.4389.128 (Official Build) (x86_64)

**Comment by ndemmel** [comment]
Duplicate. Minor bug- the search function does work, users need to click on the magnifying glass icon instead of pressing 'enter' on their keyboard.

**Comment by cherimarie** [comment]
I would agree that this is a minor usability bug. It's not clear that the magnifying glass is a clickable button.

**Comment by cherimarie** [comment]
For Jordan's grade, I won't consider this a duplicate, though for issue organization it's fine to mark it as one and keep all search changes in a single issue.
