### ISSUE TITLE
[Minor] Highlight active link on navbar

### ISSUE THREAD

**Issue by haileymeister** [info442-sp21/f-team#68]
It would be nice to include an indicator of which page you are currently on in the navbar. This will help users know which pages they have already been to so they don’t click on the same one again because they forgot they were on it.

**Comment by sienasc** [comment]
fixed

**Comment by ndemmel** [comment]
Commit that fixed this issue: https://github.com/info442-sp21/f-team/commit/494b101bb839043bae05b3015d2a39f28d9d4fb8
