### ISSUE TITLE
Menu overlap with logo on mobile [minor]

### ISSUE THREAD

**Issue by diegot-stack** [info442-sp21/f-team#69]
**Describe the bug**
When you enter the site on a mobile phone the menu and logo overlap 

**To Reproduce**
1. Enter the site on a mobile browser

**Screenshots**
![IMG_3905](https://user-images.githubusercontent.com/56012534/119575656-3fd56780-bd6c-11eb-86ae-f78de4983b2d.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: IOS 14.4.2
 - Browser [e.g. stock browser, safari]: Safari

**Comment by sienasc** [comment]
fixed

**Comment by ndemmel** [comment]
Commit that fixed this issue: https://github.com/info442-sp21/f-team/commit/6daca256645df3e611abb6acce681af9f654a629
