### ISSUE TITLE
Call to action on quiz "Next" button

### ISSUE THREAD

**Issue by gidchia** [info442-sp21/f-team#71]
**Describe the enhancement**
Would be nice to have a call to action on the quiz's "Next" buttons. Maybe have it be highlighted when hovered over.

**To Reproduce**
1. Click on "Quiz"
2. Click on "Start"
3. Click the arrow pointing right

**Desktop (please complete the following information):**

OS: iOS
Browser - Chrome
Version - Version 90.0.4430.85

**Comment by sienasc** [comment]
Duplicate of #55

**Comment by cherimarie** [comment]
For grading purposes I'm not counting this is a duplicate, but it's fine to do so for issue organization.
