### ISSUE TITLE
Quiz Page does not scale down for Mobile

### ISSUE THREAD

**Issue by gidchia** [info442-sp21/f-team#72]
**Describe the bug**
The Quiz Page doesn't scale down to fit into a mobile device's screen. The user has to manually scroll to view all the content.

**To Reproduce**
1. Go to 'Quiz'
2. See error

**Expected behavior**
Expected to see the page scale to a mobile device's screen

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [iPhone X]
 - Browser [Safari]

**Additional context**

**Comment by sienasc** [comment]
fixed

**Comment by ndemmel** [comment]
Commit that fixed this issue: https://github.com/info442-sp21/f-team/commit/9b36a4cebb1523415c2519313f13981af91b19ea
