### ISSUE TITLE
Add a favicon!

### ISSUE THREAD

**Issue by embascom** [info442-sp21/f-team#73]
Your website is so nicely designed, it would be great if you could ad a favicon to enhance your branding!

**Comment by ndemmel** [comment]
Will do :)

**Comment by dorilusions** [comment]
Added a favicon!

**Comment by ndemmel** [comment]
Commit that solved this issue: https://github.com/info442-sp21/f-team/commit/0d5412551dfa2ca229edb33ef52bc1a66fc65d57
