### ISSUE TITLE
Quiz

### ISSUE THREAD

**Issue by waheedahakim** [info442-sp21/f-team#76]
**Describe the bug**
The quiz doesnt work.

**To Reproduce**
1. Go to quiz at the top
2. Click on quiz
3. click on start
4. click on any skill level and see error

**Expected behavior**
The quiz should have more questions based on requirment.md

**Screenshots**
![image](https://user-images.githubusercontent.com/43686537/120367791-29786000-c2c6-11eb-9451-a854e36a2717.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Additional context**

**Comment by ndemmel** [comment]
Unable to reproduce behavior. Users are expected to click the arrow underneath the quiz answers (must scroll down when zoomed in like the screenshot above) to advance to the next question. Older issues address a similar usability problem with respect to the visibility of the 'next question' arrow.
