### ISSUE TITLE
Feature Request: Pet safety information in each detail page

### ISSUE THREAD

**Issue by changz23-1836696** [info442-sp21/f-team#79]
The app looks great! I'm happy to see you include a pet-related question in the quiz. However, currently, on the detail information page for each plant, there is no pet safety information. It would be better if you include that information in the detail pages or add a pet-friendly filter in the category navbar. That will save a lot of time if the user has that kind of concern.

**Comment by ndemmel** [comment]
Great suggestion! However, we will not be addressing this issue because we have decided it would take too much time to research each plant's toxicity to animals relative to the impact this addition would have on users.
